### ISSUE TITLE
разный стиль кавычек

### ISSUE THREAD

**Issue by danilaeremin** [YandexLyceumPP/Resume#5]
да вообще пройтись бы с помощью black и включить flake8 :)

**Comment by rodion-gudz** [comment]
вообще подключен deepsource, но по странному стечению обстоятельств в нем были выключены линтеры.. уже исправил, ждем фикса от него)

**Comment by rodion-gudz** [comment]
[Исправлено](https://github.com/YandexLyceumPP/Resume/commit/bfc256d9788278d1b0b2a08f747f1a79c7fd926d)
